### ISSUE TITLE
Ограничение на длину кода пользовательских полей

### ISSUE THREAD

**Issue by Dumkaaa** [marvin255/bxmigrate#1]
В Битриксе действует ограничение на длину кода пользовательских полей - не более 20 символов.
При этом 3 символа сразу "съедает" префикс `UF_`, таким образом, остается 17 символов.

```
<input type="text" name="FIELD_NAME" value="UF_" maxlength="20">
```

Прошу добавить проверку при создании миграций вида `create_user_uf_personal_country_code` (и аналогичных для других сущностей) на длину кода пользовательских полей (не более 17 символов без `UF_` или не более 20 - с ним).

**Comment by marvin255** [comment]
@Dumkaaa 

Миграция использует метод [CUserTypeEntity::Add](http://bxapi.ru/src/?module_id=main&name=CUserTypeEntity%3A%3AAdd), он в свою очередь [CUserTypeEntity::CheckFields](http://bxapi.ru/src/?module_id=main&name=CUserTypeEntity%3A%3ACheckFields), который проверяет длину имени поля. Соответственно, при слишком длинном имени поля должно будет выброситься исключение и миграция не сработает.

Таким образом, не совсем понимаю, где именно нужно будет ввести проверку.
