### ISSUE TITLE
PHP 7.1 Exeption

### ISSUE THREAD

**Issue by ultonic** [marvin255/bxmigrate#2]
Вот в этом файле /marvin255/bxmigrate/src/cli/SymphonyCreate.php вот на эту строку $repo = new Files($this->migrationPath); при php > 7 вылезает exception, так как функция construct ожидает на вход 2 параметра, а отправляется один.

**Comment by ultonic** [comment]
Соответственно в SymphonyUp, SymphonyDown и возможно еще где-то такая же проблема встречается

**Comment by marvin255** [comment]
Добавлю релиз в ближайшее время.
